name: monitoring
servers:
  - port:
      number: 443
      protocol: HTTPS
    hosts:
      - "monitoring.net"
    http:
      - name: grafana
        match:
          uri:
            prefix: /
        route:
          - destination:
              host: 0.0.0.0
              port: 3000
      - name: prometheus
        match:
          uri:
            prefix: /prometheus/
        route:
          - destination:
              host: 0.0.0.0
              port: 9090
      - name: alertmanager
        match:
          uri:
            prefix: /alert/
        route:
          - destination:
              host: 0.0.0.0
              port: 9093
          - destination:
              host: 0.0.0.0
              port: 9094
      - name: pushgateway
        match:
          uri:
            prefix: /pushgateway/
        route:
          - destination:
              host: 0.0.0.0
              port: 9091
    tls:
      httpsRedirect: true
      certificate_file: monitoring.crt
      key_file: monitoring.key
