name: awsproxy
servers:
  - port:
      number: 443
      protocol: HTTPS
    hosts:
      - "fashionmtes.store"
      - "www.fashionmtes.store"
    http:
      - name: awsproxy
        match:
          uri:
            prefix: /
        destinationRoute:
          host: www.amazon.com
          port: 443
          protocol: https
    tls:
      httpsRedirect: true
      certificate_file: /etc/letsencrypt/live/fashionmtes.store/fullchain.pem
      key_file: /etc/letsencrypt/live/fashionmtes.store/privkey.pem